---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#TODO(evrardjp): Replace the next 2 tasks by a standard apt with cache
#when https://github.com/ansible/ansible-modules-core/pull/1517 is merged
#in 1.9.x or we move to 2.0 (if tested working)
- name: Check apt last update file
  stat:
    path: /var/cache/apt
  register: apt_cache_stat
  tags:
    - haproxy-apt-packages

- name: Update apt if needed
  apt:
    update_cache: yes
  when: "ansible_date_time.epoch|float - apt_cache_stat.stat.mtime > {{cache_timeout}}"
  tags:
    - haproxy-apt-packages

- name: Install HAProxy Packages
  apt:
    pkg: "{{ item }}"
    state: latest
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: haproxy_apt_packages
  tags:
    - haproxy-apt-packages

- name: Replace haproxy DEFAULT file
  copy:
    src: haproxy.default
    dest: /etc/default/haproxy
  tags:
    - haproxy-config

- name: Replace haproxy init script to allow conf.d
  copy:
    src: haproxy.sh
    dest: /etc/init.d/haproxy
    mode: "0755"
  tags:
    - haproxy-config

- name: Create haproxy conf.d
  file:
    path: /etc/haproxy/conf.d
    state: directory
    recurse: yes
  tags:
    - haproxy-config
